default_stages: [commit]
repos:
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8

  - repo: local
    hooks:
      - id: pytest
        stages: [commit, push]
        name: pytest
        entry: pytest -v
        language: system
        pass_filenames: false
        always_run: true
